In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [3]:
encodings_to_try = ['utf-8-sig', 'latin-1', 'ISO-8859-1']

for encoding in encodings_to_try:
    try:
        df = pd.read_csv("C:/Users/15694/Desktop/Cross selling/code/Michelle/variable_without_pca2.csv", encoding=encoding)
        break
    except UnicodeDecodeError:
        continue

In [4]:
df.head()

SIX_MONTH_BAL_OS_SAVINGS  SIX_MONTH_BAL_OS_CURRENT  SIX_MONTH_BAL_OS_FD  \
0                  0.042612                 -0.048785            -0.053259   
1                 -0.091396                 -0.048785             0.066148   
2                 -0.076329                 -0.048785             0.031772   
3                 -0.101346                 -0.048785             0.308069   
4                 -0.013879                 -0.048785            -0.071656   

   SIX_MONTH_BAL_OS_LEASING  SIX_MONTH_BAL_OS_CARD  SIX_MONTH_BAL_OS_OD  \
0                 -0.134894              -0.155864            -0.075719   
1                 -0.134894              -0.297359            -0.075719   
2                 -0.134894               1.262271            -0.059430   
3                 -0.134894              -0.297359            -0.075719   
4                 -0.134894              -0.297359            -0.075719   

   TOTAL_AVG_BAL  FD_AMOUNT_UNDER_LIEN  CURRENT_AMOUNT_UNDER_LIEN  \
0      -0.062581             -0.023629                  -0.044929   
1      -0.050164             -0.023629                  -0.044929   
2      -0.065534             -0.023629                  -0.044929   
3      -0.010893             -0.023629                  -0.044929   
4      -0.053618             -0.023629                  -0.044929   

   SAVINGS_AMOUNT_UNDER_LIEN  CUSTOMER_PROFITABILITY  NO_OF_ASSERT_ACCOUNTS  \
0                  -0.056843               -0.003142               0.397017   
1                  -0.056843               -0.010305              -0.623858   
2                  -0.056843               -0.006337               1.417891   
3                  -0.056843                0.017446              -0.623858   
4                  -0.056843               -0.004448              -0.623858   

   NO_OF_LIABILITY_ACCOUNTS  CR_DR_Usage  NPA_FLAG  LOAN_CAT1  
0                  1.805905     0.051895         0          3  
1                  0.600067    -0.067204         0          3  
2                  1.805905    -0.023470         0          0  
3                  0.198120    -0.067204         0          3  
4                 -0.203826    -0.067204         1          4

In [5]:
df.columns

Index(['SIX_MONTH_BAL_OS_SAVINGS', 'SIX_MONTH_BAL_OS_CURRENT',
       'SIX_MONTH_BAL_OS_FD', 'SIX_MONTH_BAL_OS_LEASING',
       'SIX_MONTH_BAL_OS_CARD', 'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL',
       'FD_AMOUNT_UNDER_LIEN', 'CURRENT_AMOUNT_UNDER_LIEN',
       'SAVINGS_AMOUNT_UNDER_LIEN', 'CUSTOMER_PROFITABILITY',
       'NO_OF_ASSERT_ACCOUNTS', 'NO_OF_LIABILITY_ACCOUNTS', 'CR_DR_Usage',
       'NPA_FLAG', 'LOAN_CAT1'],
      dtype='object')

In [6]:
df.shape

(11836, 16)

In [7]:
df.isna().sum()

SIX_MONTH_BAL_OS_SAVINGS     0
SIX_MONTH_BAL_OS_CURRENT     0
SIX_MONTH_BAL_OS_FD          0
SIX_MONTH_BAL_OS_LEASING     0
SIX_MONTH_BAL_OS_CARD        0
SIX_MONTH_BAL_OS_OD          0
TOTAL_AVG_BAL                0
FD_AMOUNT_UNDER_LIEN         0
CURRENT_AMOUNT_UNDER_LIEN    0
SAVINGS_AMOUNT_UNDER_LIEN    0
CUSTOMER_PROFITABILITY       0
NO_OF_ASSERT_ACCOUNTS        0
NO_OF_LIABILITY_ACCOUNTS     0
CR_DR_Usage                  0
NPA_FLAG                     0
LOAN_CAT1                    0
dtype: int64

In [8]:
df.head()

SIX_MONTH_BAL_OS_SAVINGS  SIX_MONTH_BAL_OS_CURRENT  SIX_MONTH_BAL_OS_FD  \
0                  0.042612                 -0.048785            -0.053259   
1                 -0.091396                 -0.048785             0.066148   
2                 -0.076329                 -0.048785             0.031772   
3                 -0.101346                 -0.048785             0.308069   
4                 -0.013879                 -0.048785            -0.071656   

   SIX_MONTH_BAL_OS_LEASING  SIX_MONTH_BAL_OS_CARD  SIX_MONTH_BAL_OS_OD  \
0                 -0.134894              -0.155864            -0.075719   
1                 -0.134894              -0.297359            -0.075719   
2                 -0.134894               1.262271            -0.059430   
3                 -0.134894              -0.297359            -0.075719   
4                 -0.134894              -0.297359            -0.075719   

   TOTAL_AVG_BAL  FD_AMOUNT_UNDER_LIEN  CURRENT_AMOUNT_UNDER_LIEN  \
0      -0.062581             -0.023629                  -0.044929   
1      -0.050164             -0.023629                  -0.044929   
2      -0.065534             -0.023629                  -0.044929   
3      -0.010893             -0.023629                  -0.044929   
4      -0.053618             -0.023629                  -0.044929   

   SAVINGS_AMOUNT_UNDER_LIEN  CUSTOMER_PROFITABILITY  NO_OF_ASSERT_ACCOUNTS  \
0                  -0.056843               -0.003142               0.397017   
1                  -0.056843               -0.010305              -0.623858   
2                  -0.056843               -0.006337               1.417891   
3                  -0.056843                0.017446              -0.623858   
4                  -0.056843               -0.004448              -0.623858   

   NO_OF_LIABILITY_ACCOUNTS  CR_DR_Usage  NPA_FLAG  LOAN_CAT1  
0                  1.805905     0.051895         0          3  
1                  0.600067    -0.067204         0          3  
2                  1.805905    -0.023470         0          0  
3                  0.198120    -0.067204         0          3  
4                 -0.203826    -0.067204         1          4

In [9]:
df1=df[["TOTAL_AVG_BAL","CUSTOMER_PROFITABILITY","SIX_MONTH_BAL_OS_SAVINGS","SIX_MONTH_BAL_OS_FD","CR_DR_Usage",
        "SAVINGS_AMOUNT_UNDER_LIEN","LOAN_CAT1"]]

In [10]:
df1.head()

TOTAL_AVG_BAL  CUSTOMER_PROFITABILITY  SIX_MONTH_BAL_OS_SAVINGS  \
0      -0.062581               -0.003142                  0.042612   
1      -0.050164               -0.010305                 -0.091396   
2      -0.065534               -0.006337                 -0.076329   
3      -0.010893                0.017446                 -0.101346   
4      -0.053618               -0.004448                 -0.013879   

   SIX_MONTH_BAL_OS_FD  CR_DR_Usage  SAVINGS_AMOUNT_UNDER_LIEN  LOAN_CAT1  
0            -0.053259     0.051895                  -0.056843          3  
1             0.066148    -0.067204                  -0.056843          3  
2             0.031772    -0.023470                  -0.056843          0  
3             0.308069    -0.067204                  -0.056843          3  
4            -0.071656    -0.067204                  -0.056843          4

In [11]:
df1.shape

(11836, 7)

In [12]:
X = df1.drop(columns=["LOAN_CAT1"])
Y = df1["LOAN_CAT1"]

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score, f1_score,  classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

In [14]:
train_set, test_set = train_test_split(df1, test_size=0.3, random_state=0)

# Converting train_set and test_set to dataframes
train_df = pd.DataFrame(train_set)
test_df = pd.DataFrame(test_set)

In [15]:
df_cat_0 = train_df[train_df.LOAN_CAT1==0]
df_cat_1 = train_df[train_df.LOAN_CAT1==1]
df_cat_2 = train_df[train_df.LOAN_CAT1==2]
df_cat_3 = train_df[train_df.LOAN_CAT1==3]
df_cat_4 = train_df[train_df.LOAN_CAT1==4]
df_cat_5 = train_df[train_df.LOAN_CAT1==5]
df_cat_0.shape,df_cat_1.shape,df_cat_2.shape,df_cat_3.shape,df_cat_4.shape,df_cat_5.shape

((185, 7), (2006, 7), (1246, 7), (3221, 7), (796, 7), (831, 7))

In [16]:
##### The data set is imbalanced

In [17]:

X_train = train_df.drop(columns=["LOAN_CAT1"])
y_train = train_df["LOAN_CAT1"]
X_train.shape, y_train.shape

((8285, 6), (8285,))

In [18]:
X_test = test_df.drop(columns=["LOAN_CAT1"])
y_test = test_df["LOAN_CAT1"]
X_test.shape, y_test.shape

((3551, 6), (3551,))

In [19]:
from sklearn.utils import resample

In [20]:
df_majority = train_df[train_df["LOAN_CAT1"] == 3]
df_minority_1 = train_df[train_df["LOAN_CAT1"] == 0]
df_minority_2 = train_df[train_df["LOAN_CAT1"] == 1]
df_minority_3 = train_df[train_df["LOAN_CAT1"] == 2]
df_minority_4 = train_df[train_df["LOAN_CAT1"] == 4]
df_minority_5 = train_df[train_df["LOAN_CAT1"] == 5]



## oversampling

In [21]:
from sklearn.utils import resample
df_minority_1_upsampled = resample(df_minority_1, replace=True, n_samples=len(df_majority), random_state=42)
df_minority_2_upsampled = resample(df_minority_2, replace=True, n_samples=len(df_majority), random_state=42)
df_minority_3_upsampled = resample(df_minority_3, replace=True, n_samples=len(df_majority), random_state=42)
df_minority_4_upsampled = resample(df_minority_4, replace=True, n_samples=len(df_majority), random_state=42)
df_minority_5_upsampled = resample(df_minority_5, replace=True, n_samples=len(df_majority), random_state=42)

In [22]:
train_upsampled = pd.concat([df_majority,
                             df_minority_1_upsampled,
                             df_minority_2_upsampled,
                             df_minority_3_upsampled,
                             df_minority_4_upsampled,
                             df_minority_5_upsampled,
                             ])

In [23]:
train_upsampled["LOAN_CAT1"].value_counts()

3    3221
0    3221
1    3221
2    3221
4    3221
5    3221
Name: LOAN_CAT1, dtype: int64

In [24]:
X_up = train_upsampled.drop("LOAN_CAT1", axis=1)
Y_up = train_upsampled["LOAN_CAT1"]

X_up.shape, X_test.shape,Y_up.shape, y_test.shape

((19326, 6), (3551, 6), (19326,), (3551,))

In [25]:

from sklearn.ensemble import RandomForestClassifier

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score, f1_score,  classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [27]:
random_forest = RandomForestClassifier(criterion='gini',random_state=42)
random_forest.fit(X_up, Y_up)
y_pred_random_forest = random_forest.predict(X_test)

In [28]:
acc = accuracy_score(y_test, y_pred_random_forest)
prec_macro = precision_score(y_test,y_pred_random_forest, average='macro')
recall_macro = recall_score(y_test, y_pred_random_forest, average='macro')
f1_macro = f1_score(y_test,y_pred_random_forest, average='macro')
classification_rep_RF = classification_report(y_test,y_pred_random_forest)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF = confusion_matrix(y_test, y_pred_random_forest)
print("Confusion Matrix:")
print(cf_matrix_RF)
print("\nClassification Report:\n", classification_rep_RF)

Accuracy Score: 0.6744578991833287
Precision (Macro): 0.6044083835433571
Recall (Macro): 0.5850724747679407
F1 Score (Macro): 0.5928931925132206
Confusion Matrix:
[[  21   40    7    3    0    2]
 [  28  595  132   87    5    0]
 [   2  157  250  156    7    3]
 [   3   55  105 1051   78   35]
 [   0    2    2  106  177   51]
 [   0    0    0   21   69  301]]

Classification Report:
               precision    recall  f1-score   support

           0       0.39      0.29      0.33        73
           1       0.70      0.70      0.70       847
           2       0.50      0.43      0.47       575
           3       0.74      0.79      0.76      1327
           4       0.53      0.52      0.53       338
           5       0.77      0.77      0.77       391

    accuracy                           0.67      3551
   macro avg       0.60      0.59      0.59      3551
weighted avg       0.67      0.67      0.67      3551



In [29]:
y_pred_train_RF = random_forest.predict(X_up)
acc = accuracy_score(Y_up, y_pred_train_RF )
prec_macro = precision_score(Y_up,y_pred_train_RF , average='macro')
recall_macro = recall_score(Y_up, y_pred_train_RF, average='macro')
f1_macro = f1_score(Y_up, y_pred_train_RF , average='macro')
classification_rep_RF_train = classification_report(Y_up,y_pred_train_RF )
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_train = confusion_matrix(Y_up, y_pred_train_RF)
print("Confusion Matrix:")
print(cf_matrix_RF_train)
print("\nClassification Report:\n", classification_rep_RF_train)

Accuracy Score: 1.0
Precision (Macro): 1.0
Recall (Macro): 1.0
F1 Score (Macro): 1.0
Confusion Matrix:
[[3221    0    0    0    0    0]
 [   0 3221    0    0    0    0]
 [   0    0 3221    0    0    0]
 [   0    0    0 3221    0    0]
 [   0    0    0    0 3221    0]
 [   0    0    0    0    0 3221]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3221
           1       1.00      1.00      1.00      3221
           2       1.00      1.00      1.00      3221
           3       1.00      1.00      1.00      3221
           4       1.00      1.00      1.00      3221
           5       1.00      1.00      1.00      3221

    accuracy                           1.00     19326
   macro avg       1.00      1.00      1.00     19326
weighted avg       1.00      1.00      1.00     19326



In [30]:
### After tuning 

In [31]:
##### Tuning -Random search CV

In [32]:

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              }

In [33]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=0, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_up, Y_up)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=0, verbose=2)

In [34]:
rf_random.best_params_

{'n_estimators': 400,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'auto',
 'max_depth': 80}

In [35]:
best_RF_RCV = RandomForestClassifier(n_estimators= 1200,
 min_samples_split= 2,
 min_samples_leaf=1,
 max_features= 'sqrt',
 max_depth= 80,
 )
best_RF_RCV.fit(X_up, Y_up)
y_pred_RF_RCV = best_RF_RCV.predict(X_test)

In [36]:
acc = accuracy_score(y_test, y_pred_RF_RCV)
prec_macro = precision_score(y_test,y_pred_RF_RCV, average='macro')
recall_macro = recall_score(y_test, y_pred_RF_RCV, average='macro')
f1_macro = f1_score(y_test,y_pred_RF_RCV, average='macro')
classification_rep_RF_RCV = classification_report(y_test,y_pred_RF_RCV)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_rcv = confusion_matrix(y_test, y_pred_RF_RCV)
print("Confusion Matrix:")
print(cf_matrix_RF_rcv)
print("\nClassification Report:\n", classification_rep_RF_RCV)

Accuracy Score: 0.6755843424387497
Precision (Macro): 0.6063627480351474
Recall (Macro): 0.5841168564280592
F1 Score (Macro): 0.5928710126673836
Confusion Matrix:
[[  20   43    5    3    0    2]
 [  27  592  132   91    5    0]
 [   2  150  258  155    6    4]
 [   2   56  107 1051   77   34]
 [   0    2    1  109  171   55]
 [   0    0    0   22   62  307]]

Classification Report:
               precision    recall  f1-score   support

           0       0.39      0.27      0.32        73
           1       0.70      0.70      0.70       847
           2       0.51      0.45      0.48       575
           3       0.73      0.79      0.76      1327
           4       0.53      0.51      0.52       338
           5       0.76      0.79      0.77       391

    accuracy                           0.68      3551
   macro avg       0.61      0.58      0.59      3551
weighted avg       0.67      0.68      0.67      3551



In [37]:
y_pred_RF_RCV_train = best_RF_RCV.predict(X_up)

In [38]:
acc = accuracy_score(Y_up, y_pred_RF_RCV_train)
prec_macro = precision_score(Y_up,y_pred_RF_RCV_train, average='macro')
recall_macro = recall_score(Y_up, y_pred_RF_RCV_train, average='macro')
f1_macro = f1_score(Y_up,y_pred_RF_RCV_train, average='macro')
classification_rep_RF_RCV_Train = classification_report(Y_up,y_pred_RF_RCV_train)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_rcv_train = confusion_matrix(Y_up, y_pred_RF_RCV_train)
print("Confusion Matrix:")
print(cf_matrix_RF_rcv_train)
print("\nClassification Report:\n", classification_rep_RF_RCV_Train)

Accuracy Score: 1.0
Precision (Macro): 1.0
Recall (Macro): 1.0
F1 Score (Macro): 1.0
Confusion Matrix:
[[3221    0    0    0    0    0]
 [   0 3221    0    0    0    0]
 [   0    0 3221    0    0    0]
 [   0    0    0 3221    0    0]
 [   0    0    0    0 3221    0]
 [   0    0    0    0    0 3221]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3221
           1       1.00      1.00      1.00      3221
           2       1.00      1.00      1.00      3221
           3       1.00      1.00      1.00      3221
           4       1.00      1.00      1.00      3221
           5       1.00      1.00      1.00      3221

    accuracy                           1.00     19326
   macro avg       1.00      1.00      1.00     19326
weighted avg       1.00      1.00      1.00     19326



In [39]:
### Gridsearch CV

In [40]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [rf_random.best_params_['max_depth']],
    'max_features': [rf_random.best_params_['max_features']],
    'min_samples_leaf': [rf_random.best_params_['min_samples_leaf'], 
                         rf_random.best_params_['min_samples_leaf']+2, 
                         rf_random.best_params_['min_samples_leaf'] + 4],
    'min_samples_split': [rf_random.best_params_['min_samples_split'] - 2,
                          rf_random.best_params_['min_samples_split'] - 1,
                          rf_random.best_params_['min_samples_split'], 
                          rf_random.best_params_['min_samples_split'] +1,
                          rf_random.best_params_['min_samples_split'] + 2],
    'n_estimators': [rf_random.best_params_['n_estimators'] - 200, rf_random.best_params_['n_estimators'] - 100, 
                     rf_random.best_params_['n_estimators'], 
                     rf_random.best_params_['n_estimators'] + 100, rf_random.best_params_['n_estimators'] + 200]
}

print(param_grid)
# Create a based model


{'max_depth': [80], 'max_features': ['auto'], 'min_samples_leaf': [1, 3, 5], 'min_samples_split': [0, 1, 2, 3, 4], 'n_estimators': [200, 300, 400, 500, 600]}


In [41]:
RF = RandomForestClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = RF, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)
grid_search.fit(X_up,Y_up)

Fitting 3 folds for each of 75 candidates, totalling 225 fits


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
90 fits failed out of a total of 225.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\ProgramData\anaconda3\Lib\site-packag

GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [80], 'max_features': ['auto'],
                         'min_samples_leaf': [1, 3, 5],
                         'min_samples_split': [0, 1, 2, 3, 4],
                         'n_estimators': [200, 300, 400, 500, 600]},
             verbose=2)

In [42]:
grid_search.best_estimator_

RandomForestClassifier(max_depth=80, max_features='auto', n_estimators=500)

In [53]:
best_RF_GCV=RandomForestClassifier(max_depth=80, n_estimators=500,max_features='auto')
best_RF_GCV.fit(X_up, Y_up)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


RandomForestClassifier(max_depth=80, max_features='auto', n_estimators=500)

In [58]:
y_pred_RF_GCV = best_RF_GCV.predict(X_test)

In [59]:


acc = accuracy_score(y_test, y_pred_RF_GCV)
prec_macro = precision_score(y_test,y_pred_RF_GCV, average='macro')
recall_macro = recall_score(y_test, y_pred_RF_GCV, average='macro')
f1_macro = f1_score(y_test,y_pred_RF_GCV, average='macro')
classification_rep_RF_GCV = classification_report(y_test,y_pred_RF_GCV)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_gcv = confusion_matrix(y_test, y_pred_RF_GCV)
print("Confusion Matrix:")
print(cf_matrix_RF_gcv)
print("\nClassification Report:\n", classification_rep_RF_GCV)

Accuracy Score: 0.6733314559279077
Precision (Macro): 0.6071173514733581
Recall (Macro): 0.5841909591163709
F1 Score (Macro): 0.593332772731113
Confusion Matrix:
[[  21   41    4    5    0    2]
 [  28  593  129   93    4    0]
 [   1  157  251  156    5    5]
 [   2   55  113 1048   77   32]
 [   0    2    1  110  171   54]
 [   0    0    0   23   61  307]]

Classification Report:
               precision    recall  f1-score   support

           0       0.40      0.29      0.34        73
           1       0.70      0.70      0.70       847
           2       0.50      0.44      0.47       575
           3       0.73      0.79      0.76      1327
           4       0.54      0.51      0.52       338
           5       0.77      0.79      0.78       391

    accuracy                           0.67      3551
   macro avg       0.61      0.58      0.59      3551
weighted avg       0.67      0.67      0.67      3551



In [60]:
y_pred_RF_GCV_train = best_RF_GCV.predict(X_up)

In [61]:
acc1 = accuracy_score(Y_up, y_pred_RF_GCV_train)
prec_macro1 = precision_score(Y_up,y_pred_RF_GCV_train, average='macro')
recall_macro1 = recall_score(Y_up, y_pred_RF_GCV_train, average='macro')
f1_macro1 = f1_score(Y_up,y_pred_RF_GCV_train, average='macro')
classification_rep_RF_GCV_Train = classification_report(Y_up,y_pred_RF_GCV_train)
print("Accuracy Score:", acc1)
print("Precision (Macro):", prec_macro1)
print("Recall (Macro):", recall_macro1)
print("F1 Score (Macro):", f1_macro1)

# Confusion Matrix
cf_matrix_RF_gcv_train = confusion_matrix(Y_up, y_pred_RF_GCV_train)
print("Confusion Matrix:")
print(cf_matrix_RF_gcv_train)
print("\nClassification Report:\n", classification_rep_RF_GCV_Train)

Accuracy Score: 1.0
Precision (Macro): 1.0
Recall (Macro): 1.0
F1 Score (Macro): 1.0
Confusion Matrix:
[[3221    0    0    0    0    0]
 [   0 3221    0    0    0    0]
 [   0    0 3221    0    0    0]
 [   0    0    0 3221    0    0]
 [   0    0    0    0 3221    0]
 [   0    0    0    0    0 3221]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3221
           1       1.00      1.00      1.00      3221
           2       1.00      1.00      1.00      3221
           3       1.00      1.00      1.00      3221
           4       1.00      1.00      1.00      3221
           5       1.00      1.00      1.00      3221

    accuracy                           1.00     19326
   macro avg       1.00      1.00      1.00     19326
weighted avg       1.00      1.00      1.00     19326

