In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [3]:
encodings_to_try = ['utf-8-sig', 'latin-1', 'ISO-8859-1']

for encoding in encodings_to_try:
    try:
        df = pd.read_csv("C:/Users/15694/Desktop/Cross selling/code/Michelle/variable_without_pca2.csv", encoding=encoding)
        break
    except UnicodeDecodeError:
        continue

In [4]:
df.head()

SIX_MONTH_BAL_OS_SAVINGS  SIX_MONTH_BAL_OS_CURRENT  SIX_MONTH_BAL_OS_FD  \
0                  0.042612                 -0.048785            -0.053259   
1                 -0.091396                 -0.048785             0.066148   
2                 -0.076329                 -0.048785             0.031772   
3                 -0.101346                 -0.048785             0.308069   
4                 -0.013879                 -0.048785            -0.071656   

   SIX_MONTH_BAL_OS_LEASING  SIX_MONTH_BAL_OS_CARD  SIX_MONTH_BAL_OS_OD  \
0                 -0.134894              -0.155864            -0.075719   
1                 -0.134894              -0.297359            -0.075719   
2                 -0.134894               1.262271            -0.059430   
3                 -0.134894              -0.297359            -0.075719   
4                 -0.134894              -0.297359            -0.075719   

   TOTAL_AVG_BAL  FD_AMOUNT_UNDER_LIEN  CURRENT_AMOUNT_UNDER_LIEN  \
0      -0.062581             -0.023629                  -0.044929   
1      -0.050164             -0.023629                  -0.044929   
2      -0.065534             -0.023629                  -0.044929   
3      -0.010893             -0.023629                  -0.044929   
4      -0.053618             -0.023629                  -0.044929   

   SAVINGS_AMOUNT_UNDER_LIEN  CUSTOMER_PROFITABILITY  NO_OF_ASSERT_ACCOUNTS  \
0                  -0.056843               -0.003142               0.397017   
1                  -0.056843               -0.010305              -0.623858   
2                  -0.056843               -0.006337               1.417891   
3                  -0.056843                0.017446              -0.623858   
4                  -0.056843               -0.004448              -0.623858   

   NO_OF_LIABILITY_ACCOUNTS  CR_DR_Usage  NPA_FLAG  LOAN_CAT1  
0                  1.805905     0.051895         0          3  
1                  0.600067    -0.067204         0          3  
2                  1.805905    -0.023470         0          0  
3                  0.198120    -0.067204         0          3  
4                 -0.203826    -0.067204         1          4

In [5]:
df.columns

Index(['SIX_MONTH_BAL_OS_SAVINGS', 'SIX_MONTH_BAL_OS_CURRENT',
       'SIX_MONTH_BAL_OS_FD', 'SIX_MONTH_BAL_OS_LEASING',
       'SIX_MONTH_BAL_OS_CARD', 'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL',
       'FD_AMOUNT_UNDER_LIEN', 'CURRENT_AMOUNT_UNDER_LIEN',
       'SAVINGS_AMOUNT_UNDER_LIEN', 'CUSTOMER_PROFITABILITY',
       'NO_OF_ASSERT_ACCOUNTS', 'NO_OF_LIABILITY_ACCOUNTS', 'CR_DR_Usage',
       'NPA_FLAG', 'LOAN_CAT1'],
      dtype='object')

In [6]:
df.shape

(11836, 16)

In [7]:
df.isna().sum()

SIX_MONTH_BAL_OS_SAVINGS     0
SIX_MONTH_BAL_OS_CURRENT     0
SIX_MONTH_BAL_OS_FD          0
SIX_MONTH_BAL_OS_LEASING     0
SIX_MONTH_BAL_OS_CARD        0
SIX_MONTH_BAL_OS_OD          0
TOTAL_AVG_BAL                0
FD_AMOUNT_UNDER_LIEN         0
CURRENT_AMOUNT_UNDER_LIEN    0
SAVINGS_AMOUNT_UNDER_LIEN    0
CUSTOMER_PROFITABILITY       0
NO_OF_ASSERT_ACCOUNTS        0
NO_OF_LIABILITY_ACCOUNTS     0
CR_DR_Usage                  0
NPA_FLAG                     0
LOAN_CAT1                    0
dtype: int64

In [8]:
df1=df[["TOTAL_AVG_BAL","CUSTOMER_PROFITABILITY","SIX_MONTH_BAL_OS_SAVINGS","SIX_MONTH_BAL_OS_FD","CR_DR_Usage",
        "SIX_MONTH_BAL_OS_CARD","LOAN_CAT1"]]

In [9]:
df1.head()

TOTAL_AVG_BAL  CUSTOMER_PROFITABILITY  SIX_MONTH_BAL_OS_SAVINGS  \
0      -0.062581               -0.003142                  0.042612   
1      -0.050164               -0.010305                 -0.091396   
2      -0.065534               -0.006337                 -0.076329   
3      -0.010893                0.017446                 -0.101346   
4      -0.053618               -0.004448                 -0.013879   

   SIX_MONTH_BAL_OS_FD  CR_DR_Usage  SIX_MONTH_BAL_OS_CARD  LOAN_CAT1  
0            -0.053259     0.051895              -0.155864          3  
1             0.066148    -0.067204              -0.297359          3  
2             0.031772    -0.023470               1.262271          0  
3             0.308069    -0.067204              -0.297359          3  
4            -0.071656    -0.067204              -0.297359          4

In [10]:
X = df.drop(columns=["LOAN_CAT1"])
Y = df["LOAN_CAT1"]

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score, f1_score,  classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [12]:
train_set, test_set = train_test_split(df, test_size=0.3, random_state=0)

# Converting train_set and test_set to dataframes
train_df = pd.DataFrame(train_set)
test_df = pd.DataFrame(test_set)

In [13]:
df_cat_0 = train_df[train_df.LOAN_CAT1==0]
df_cat_1 = train_df[train_df.LOAN_CAT1==1]
df_cat_2 = train_df[train_df.LOAN_CAT1==2]
df_cat_3 = train_df[train_df.LOAN_CAT1==3]
df_cat_4 = train_df[train_df.LOAN_CAT1==4]
df_cat_5 = train_df[train_df.LOAN_CAT1==5]
df_cat_0.shape,df_cat_1.shape,df_cat_2.shape,df_cat_3.shape,df_cat_4.shape,df_cat_5.shape

((185, 16), (2006, 16), (1246, 16), (3221, 16), (796, 16), (831, 16))

In [14]:
##### The data set is imbalanced

In [15]:

X_train = train_df.drop(columns=["LOAN_CAT1"])
y_train = train_df["LOAN_CAT1"]
X_train.shape, y_train.shape

((8285, 15), (8285,))

In [16]:
X_test = test_df.drop(columns=["LOAN_CAT1"])
y_test = test_df["LOAN_CAT1"]
X_test.shape, y_test.shape

((3551, 15), (3551,))

In [17]:
from sklearn.utils import resample

In [18]:
df_minority = train_df[train_df["LOAN_CAT1"] == 0]
df_majority_1 = train_df[train_df["LOAN_CAT1"] == 1]
df_majority_2 = train_df[train_df["LOAN_CAT1"] == 2]
df_majority_3 = train_df[train_df["LOAN_CAT1"] == 3]
df_majority_4 = train_df[train_df["LOAN_CAT1"] == 4]
df_majority_5 = train_df[train_df["LOAN_CAT1"] == 5]


## Undersampling

In [19]:
from sklearn.utils import resample
df_majority_1_downsampled = resample(df_majority_1, replace=True, n_samples=len(df_minority), random_state=42)
df_majority_2_downsampled = resample(df_majority_2, replace=True, n_samples=len(df_minority), random_state=42)
df_majority_3_downsampled = resample(df_majority_3, replace=True, n_samples=len(df_minority), random_state=42)
df_majority_4_downsampled = resample(df_majority_4, replace=True, n_samples=len(df_minority), random_state=42)
df_majority_5_downsampled = resample(df_majority_5, replace=True, n_samples=len(df_minority), random_state=42)

In [20]:
train_downsampled = pd.concat([df_minority,
                             df_majority_1_downsampled,
                             df_majority_2_downsampled,
                             df_majority_3_downsampled,
                             df_majority_4_downsampled,
                             df_majority_5_downsampled,
                             ])

In [21]:
train_downsampled["LOAN_CAT1"].value_counts()

0    185
1    185
2    185
3    185
4    185
5    185
Name: LOAN_CAT1, dtype: int64

In [22]:
X_under = train_downsampled.drop("LOAN_CAT1", axis=1)
Y_under = train_downsampled["LOAN_CAT1"]

X_under.shape, X_test.shape,X_under.shape, y_test.shape

((1110, 15), (3551, 15), (1110, 15), (3551,))

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
random_forest = RandomForestClassifier(criterion='gini',random_state=0)
random_forest.fit(X_under, Y_under)
y_pred_random_forest = random_forest.predict(X_test)

In [25]:
acc = accuracy_score(y_test, y_pred_random_forest)
prec_macro = precision_score(y_test,y_pred_random_forest, average='macro')
recall_macro = recall_score(y_test, y_pred_random_forest, average='macro')
f1_macro = f1_score(y_test,y_pred_random_forest, average='macro')
classification_rep_RF = classification_report(y_test,y_pred_random_forest)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF = confusion_matrix(y_test, y_pred_random_forest)
print("Confusion Matrix:")
print(cf_matrix_RF)
print("\nClassification Report:\n", classification_rep_RF)

Accuracy Score: 0.5927907631653055
Precision (Macro): 0.5410048083372833
Recall (Macro): 0.6183467218201475
F1 Score (Macro): 0.5438184605897801
Confusion Matrix:
[[ 47  13   7   4   0   2]
 [176 370 224  60  15   2]
 [ 27  96 304 119  21   8]
 [ 18  22 191 847 199  50]
 [  2   0   4  44 222  66]
 [  0   0   0  11  65 315]]

Classification Report:
               precision    recall  f1-score   support

           0       0.17      0.64      0.27        73
           1       0.74      0.44      0.55       847
           2       0.42      0.53      0.47       575
           3       0.78      0.64      0.70      1327
           4       0.43      0.66      0.52       338
           5       0.71      0.81      0.76       391

    accuracy                           0.59      3551
   macro avg       0.54      0.62      0.54      3551
weighted avg       0.66      0.59      0.61      3551



In [26]:
y_pred_train_RF = random_forest.predict(X_under)
acc = accuracy_score(Y_under, y_pred_train_RF )
prec_macro = precision_score(Y_under,y_pred_train_RF , average='macro')
recall_macro = recall_score(Y_under, y_pred_train_RF, average='macro')
f1_macro = f1_score(Y_under, y_pred_train_RF , average='macro')
classification_rep_RF_train = classification_report(Y_under,y_pred_train_RF )
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_train = confusion_matrix(Y_under, y_pred_train_RF)
print("Confusion Matrix:")
print(cf_matrix_RF_train)
print("\nClassification Report:\n", classification_rep_RF_train)


Accuracy Score: 1.0
Precision (Macro): 1.0
Recall (Macro): 1.0
F1 Score (Macro): 1.0
Confusion Matrix:
[[185   0   0   0   0   0]
 [  0 185   0   0   0   0]
 [  0   0 185   0   0   0]
 [  0   0   0 185   0   0]
 [  0   0   0   0 185   0]
 [  0   0   0   0   0 185]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       185
           1       1.00      1.00      1.00       185
           2       1.00      1.00      1.00       185
           3       1.00      1.00      1.00       185
           4       1.00      1.00      1.00       185
           5       1.00      1.00      1.00       185

    accuracy                           1.00      1110
   macro avg       1.00      1.00      1.00      1110
weighted avg       1.00      1.00      1.00      1110



In [27]:

n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]

random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              }

In [28]:
##### Tuning -Random search CV

In [29]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              }

In [30]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=0, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_under, Y_under)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=0, verbose=2)

In [31]:
rf_random.best_params_

{'n_estimators': 200,
 'min_samples_split': 10,
 'min_samples_leaf': 1,
 'max_features': 'auto',
 'max_depth': 20}

In [45]:
best_RF_RCV = RandomForestClassifier(n_estimators= 200,
 min_samples_split= 10,
 min_samples_leaf=1,
 max_features= 'auto',
 max_depth= 20,
 )
best_RF_RCV.fit(X_under, Y_under)
y_pred_RF_RCV = best_RF_RCV.predict(X_test)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


In [46]:
acc = accuracy_score(y_test, y_pred_RF_RCV)
prec_macro = precision_score(y_test,y_pred_RF_RCV, average='macro')
recall_macro = recall_score(y_test, y_pred_RF_RCV, average='macro')
f1_macro = f1_score(y_test,y_pred_RF_RCV, average='macro')
classification_rep_RF_RCV = classification_report(y_test,y_pred_RF_RCV)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_rcv = confusion_matrix(y_test, y_pred_RF_RCV)
print("Confusion Matrix:")
print(cf_matrix_RF_rcv)
print("\nClassification Report:\n", classification_rep_RF_RCV)

Accuracy Score: 0.5947620388622923
Precision (Macro): 0.5456859323500769
Recall (Macro): 0.6303748244200169
F1 Score (Macro): 0.5483492596499211
Confusion Matrix:
[[ 51  12   6   2   0   2]
 [171 366 215  74  18   3]
 [ 27  87 305 121  28   7]
 [ 15  15 182 846 214  55]
 [  1   0   4  36 230  67]
 [  0   0   1   9  67 314]]

Classification Report:
               precision    recall  f1-score   support

           0       0.19      0.70      0.30        73
           1       0.76      0.43      0.55       847
           2       0.43      0.53      0.47       575
           3       0.78      0.64      0.70      1327
           4       0.41      0.68      0.51       338
           5       0.70      0.80      0.75       391

    accuracy                           0.59      3551
   macro avg       0.55      0.63      0.55      3551
weighted avg       0.66      0.59      0.61      3551



In [47]:
y_pred_RF_RCV_train = best_RF_RCV.predict(X_under)

In [48]:
acc = accuracy_score(Y_under, y_pred_RF_RCV_train)
prec_macro = precision_score(Y_under,y_pred_RF_RCV_train, average='macro')
recall_macro = recall_score(Y_under, y_pred_RF_RCV_train, average='macro')
f1_macro = f1_score(Y_under,y_pred_RF_RCV_train, average='macro')
classification_rep_RF_RCV_Train = classification_report(Y_under,y_pred_RF_RCV_train)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_rcv_train = confusion_matrix(Y_under, y_pred_RF_RCV_train)
print("Confusion Matrix:")
print(cf_matrix_RF_rcv_train)
print("\nClassification Report:\n", classification_rep_RF_RCV_Train)

Accuracy Score: 0.9162162162162162
Precision (Macro): 0.9165772201160753
Recall (Macro): 0.9162162162162163
F1 Score (Macro): 0.9159744824616527
Confusion Matrix:
[[173   6   2   2   1   1]
 [  8 165   6   5   1   0]
 [  2   8 171   2   1   1]
 [  0   1  11 164   7   2]
 [  0   0   0   7 163  15]
 [  0   1   0   1   2 181]]

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.94      0.94       185
           1       0.91      0.89      0.90       185
           2       0.90      0.92      0.91       185
           3       0.91      0.89      0.90       185
           4       0.93      0.88      0.91       185
           5       0.91      0.98      0.94       185

    accuracy                           0.92      1110
   macro avg       0.92      0.92      0.92      1110
weighted avg       0.92      0.92      0.92      1110



In [49]:
### Gridsearch CV

In [50]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [rf_random.best_params_['max_depth']],
    'max_features': [rf_random.best_params_['max_features']],
    'min_samples_leaf': [rf_random.best_params_['min_samples_leaf'], 
                         rf_random.best_params_['min_samples_leaf']+2, 
                         rf_random.best_params_['min_samples_leaf'] + 4],
    'min_samples_split': [rf_random.best_params_['min_samples_split'] - 2,
                          rf_random.best_params_['min_samples_split'] - 1,
                          rf_random.best_params_['min_samples_split'], 
                          rf_random.best_params_['min_samples_split'] +1,
                          rf_random.best_params_['min_samples_split'] + 2],
    'n_estimators': [rf_random.best_params_['n_estimators'] - 200, rf_random.best_params_['n_estimators'] - 100, 
                     rf_random.best_params_['n_estimators'], 
                     rf_random.best_params_['n_estimators'] + 100, rf_random.best_params_['n_estimators'] + 200]
}

print(param_grid)
# Create a based model

{'max_depth': [20], 'max_features': ['auto'], 'min_samples_leaf': [1, 3, 5], 'min_samples_split': [8, 9, 10, 11, 12], 'n_estimators': [0, 100, 200, 300, 400]}


In [51]:
RF = RandomForestClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = RF, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)
grid_search.fit(X_under,Y_under)

Fitting 3 folds for each of 75 candidates, totalling 225 fits


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
45 fits failed out of a total of 225.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\ProgramData\anaconda3\Lib\site-packag

GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [20], 'max_features': ['auto'],
                         'min_samples_leaf': [1, 3, 5],
                         'min_samples_split': [8, 9, 10, 11, 12],
                         'n_estimators': [0, 100, 200, 300, 400]},
             verbose=2)

In [52]:
grid_search.best_estimator_

RandomForestClassifier(max_depth=20, max_features='auto', min_samples_split=10)

In [53]:
best_RF_GCV=RandomForestClassifier(max_depth=20,  min_samples_split=11,
                       max_features='auto')
best_RF_GCV.fit(X_under, Y_under)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


RandomForestClassifier(max_depth=20, max_features='auto', min_samples_split=11)

In [54]:
y_pred_RF_GCV = best_RF_GCV.predict(X_test)

In [55]:

acc = accuracy_score(y_test, y_pred_RF_GCV)
prec_macro = precision_score(y_test,y_pred_RF_GCV, average='macro')
recall_macro = recall_score(y_test, y_pred_RF_GCV, average='macro')
f1_macro = f1_score(y_test,y_pred_RF_GCV, average='macro')
classification_rep_RF_GCV = classification_report(y_test,y_pred_RF_GCV)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_gcv = confusion_matrix(y_test, y_pred_RF_GCV)
print("Confusion Matrix:")
print(cf_matrix_RF_gcv)
print("\nClassification Report:\n", classification_rep_RF_GCV)

Accuracy Score: 0.5894114333990426
Precision (Macro): 0.5407237330951384
Recall (Macro): 0.6162962669375068
F1 Score (Macro): 0.5396054426820419
Confusion Matrix:
[[ 47  15   6   3   0   2]
 [182 352 226  63  23   1]
 [ 27  85 315 113  29   6]
 [ 15  17 188 846 209  52]
 [  1   0   2  44 224  67]
 [  0   0   2   8  72 309]]

Classification Report:
               precision    recall  f1-score   support

           0       0.17      0.64      0.27        73
           1       0.75      0.42      0.53       847
           2       0.43      0.55      0.48       575
           3       0.79      0.64      0.70      1327
           4       0.40      0.66      0.50       338
           5       0.71      0.79      0.75       391

    accuracy                           0.59      3551
   macro avg       0.54      0.62      0.54      3551
weighted avg       0.66      0.59      0.60      3551



In [56]:
y_pred_RF_GCV_train = best_RF_GCV.predict(X_under)

In [57]:
acc = accuracy_score(Y_under, y_pred_RF_GCV_train)
prec_macro = precision_score(Y_under,y_pred_RF_GCV_train, average='macro')
recall_macro = recall_score(Y_under, y_pred_RF_GCV_train, average='macro')
f1_macro = f1_score(Y_under,y_pred_RF_GCV_train, average='macro')
classification_rep_RF_GCV_Train = classification_report(Y_under,y_pred_RF_GCV_train)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_gcv_train = confusion_matrix(Y_under, y_pred_RF_GCV_train)
print("Confusion Matrix:")
print(cf_matrix_RF_gcv_train)
print("\nClassification Report:\n", classification_rep_RF_GCV_Train)

Accuracy Score: 0.9108108108108108
Precision (Macro): 0.9112839761533639
Recall (Macro): 0.9108108108108107
F1 Score (Macro): 0.9106076975638512
Confusion Matrix:
[[164   9   4   6   1   1]
 [ 10 165   6   3   1   0]
 [  2   7 171   1   2   2]
 [  0   1  12 164   6   2]
 [  0   0   1   6 166  12]
 [  0   1   0   1   2 181]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.89      0.91       185
           1       0.90      0.89      0.90       185
           2       0.88      0.92      0.90       185
           3       0.91      0.89      0.90       185
           4       0.93      0.90      0.91       185
           5       0.91      0.98      0.95       185

    accuracy                           0.91      1110
   macro avg       0.91      0.91      0.91      1110
weighted avg       0.91      0.91      0.91      1110

