In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [3]:
encodings_to_try = ['utf-8-sig', 'latin-1', 'ISO-8859-1']

for encoding in encodings_to_try:
    try:
        df = pd.read_csv("C:/Users/15694/Desktop/Cross selling/code/Michelle/variable_without_pca2.csv", encoding=encoding)
        break
    except UnicodeDecodeError:
        continue

In [4]:
df.head()

SIX_MONTH_BAL_OS_SAVINGS  SIX_MONTH_BAL_OS_CURRENT  SIX_MONTH_BAL_OS_FD  \
0                  0.042612                 -0.048785            -0.053259   
1                 -0.091396                 -0.048785             0.066148   
2                 -0.076329                 -0.048785             0.031772   
3                 -0.101346                 -0.048785             0.308069   
4                 -0.013879                 -0.048785            -0.071656   

   SIX_MONTH_BAL_OS_LEASING  SIX_MONTH_BAL_OS_CARD  SIX_MONTH_BAL_OS_OD  \
0                 -0.134894              -0.155864            -0.075719   
1                 -0.134894              -0.297359            -0.075719   
2                 -0.134894               1.262271            -0.059430   
3                 -0.134894              -0.297359            -0.075719   
4                 -0.134894              -0.297359            -0.075719   

   TOTAL_AVG_BAL  FD_AMOUNT_UNDER_LIEN  CURRENT_AMOUNT_UNDER_LIEN  \
0      -0.062581             -0.023629                  -0.044929   
1      -0.050164             -0.023629                  -0.044929   
2      -0.065534             -0.023629                  -0.044929   
3      -0.010893             -0.023629                  -0.044929   
4      -0.053618             -0.023629                  -0.044929   

   SAVINGS_AMOUNT_UNDER_LIEN  CUSTOMER_PROFITABILITY  NO_OF_ASSERT_ACCOUNTS  \
0                  -0.056843               -0.003142               0.397017   
1                  -0.056843               -0.010305              -0.623858   
2                  -0.056843               -0.006337               1.417891   
3                  -0.056843                0.017446              -0.623858   
4                  -0.056843               -0.004448              -0.623858   

   NO_OF_LIABILITY_ACCOUNTS  CR_DR_Usage  NPA_FLAG  LOAN_CAT1  
0                  1.805905     0.051895         0          3  
1                  0.600067    -0.067204         0          3  
2                  1.805905    -0.023470         0          0  
3                  0.198120    -0.067204         0          3  
4                 -0.203826    -0.067204         1          4

In [5]:
df.columns

Index(['SIX_MONTH_BAL_OS_SAVINGS', 'SIX_MONTH_BAL_OS_CURRENT',
       'SIX_MONTH_BAL_OS_FD', 'SIX_MONTH_BAL_OS_LEASING',
       'SIX_MONTH_BAL_OS_CARD', 'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL',
       'FD_AMOUNT_UNDER_LIEN', 'CURRENT_AMOUNT_UNDER_LIEN',
       'SAVINGS_AMOUNT_UNDER_LIEN', 'CUSTOMER_PROFITABILITY',
       'NO_OF_ASSERT_ACCOUNTS', 'NO_OF_LIABILITY_ACCOUNTS', 'CR_DR_Usage',
       'NPA_FLAG', 'LOAN_CAT1'],
      dtype='object')

In [6]:
df.shape

(11836, 16)

In [7]:
df.isna().sum()

SIX_MONTH_BAL_OS_SAVINGS     0
SIX_MONTH_BAL_OS_CURRENT     0
SIX_MONTH_BAL_OS_FD          0
SIX_MONTH_BAL_OS_LEASING     0
SIX_MONTH_BAL_OS_CARD        0
SIX_MONTH_BAL_OS_OD          0
TOTAL_AVG_BAL                0
FD_AMOUNT_UNDER_LIEN         0
CURRENT_AMOUNT_UNDER_LIEN    0
SAVINGS_AMOUNT_UNDER_LIEN    0
CUSTOMER_PROFITABILITY       0
NO_OF_ASSERT_ACCOUNTS        0
NO_OF_LIABILITY_ACCOUNTS     0
CR_DR_Usage                  0
NPA_FLAG                     0
LOAN_CAT1                    0
dtype: int64

In [8]:
df.head()

SIX_MONTH_BAL_OS_SAVINGS  SIX_MONTH_BAL_OS_CURRENT  SIX_MONTH_BAL_OS_FD  \
0                  0.042612                 -0.048785            -0.053259   
1                 -0.091396                 -0.048785             0.066148   
2                 -0.076329                 -0.048785             0.031772   
3                 -0.101346                 -0.048785             0.308069   
4                 -0.013879                 -0.048785            -0.071656   

   SIX_MONTH_BAL_OS_LEASING  SIX_MONTH_BAL_OS_CARD  SIX_MONTH_BAL_OS_OD  \
0                 -0.134894              -0.155864            -0.075719   
1                 -0.134894              -0.297359            -0.075719   
2                 -0.134894               1.262271            -0.059430   
3                 -0.134894              -0.297359            -0.075719   
4                 -0.134894              -0.297359            -0.075719   

   TOTAL_AVG_BAL  FD_AMOUNT_UNDER_LIEN  CURRENT_AMOUNT_UNDER_LIEN  \
0      -0.062581             -0.023629                  -0.044929   
1      -0.050164             -0.023629                  -0.044929   
2      -0.065534             -0.023629                  -0.044929   
3      -0.010893             -0.023629                  -0.044929   
4      -0.053618             -0.023629                  -0.044929   

   SAVINGS_AMOUNT_UNDER_LIEN  CUSTOMER_PROFITABILITY  NO_OF_ASSERT_ACCOUNTS  \
0                  -0.056843               -0.003142               0.397017   
1                  -0.056843               -0.010305              -0.623858   
2                  -0.056843               -0.006337               1.417891   
3                  -0.056843                0.017446              -0.623858   
4                  -0.056843               -0.004448              -0.623858   

   NO_OF_LIABILITY_ACCOUNTS  CR_DR_Usage  NPA_FLAG  LOAN_CAT1  
0                  1.805905     0.051895         0          3  
1                  0.600067    -0.067204         0          3  
2                  1.805905    -0.023470         0          0  
3                  0.198120    -0.067204         0          3  
4                 -0.203826    -0.067204         1          4

In [9]:
df1=df[["TOTAL_AVG_BAL","CUSTOMER_PROFITABILITY","SIX_MONTH_BAL_OS_SAVINGS","SIX_MONTH_BAL_OS_FD","CR_DR_Usage"
        ,"NO_OF_LIABILITY_ACCOUNTS","LOAN_CAT1"]]

In [10]:
df1.head()

TOTAL_AVG_BAL  CUSTOMER_PROFITABILITY  SIX_MONTH_BAL_OS_SAVINGS  \
0      -0.062581               -0.003142                  0.042612   
1      -0.050164               -0.010305                 -0.091396   
2      -0.065534               -0.006337                 -0.076329   
3      -0.010893                0.017446                 -0.101346   
4      -0.053618               -0.004448                 -0.013879   

   SIX_MONTH_BAL_OS_FD  CR_DR_Usage  NO_OF_LIABILITY_ACCOUNTS  LOAN_CAT1  
0            -0.053259     0.051895                  1.805905          3  
1             0.066148    -0.067204                  0.600067          3  
2             0.031772    -0.023470                  1.805905          0  
3             0.308069    -0.067204                  0.198120          3  
4            -0.071656    -0.067204                 -0.203826          4

In [11]:
df1.shape

(11836, 7)

In [12]:
X = df1.drop(columns=["LOAN_CAT1"])
Y = df1["LOAN_CAT1"]

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score, f1_score,  classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [15]:
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import SMOTENC
from collections import Counter
sm = SMOTE()
X_sm, Y_sm=sm.fit_resample(X_train,y_train)
print('Dataset after resampling:')
print(sorted(Counter(Y_sm).items()))

Dataset after resampling:
[(0, 3221), (1, 3221), (2, 3221), (3, 3221), (4, 3221), (5, 3221)]


In [16]:

from sklearn.ensemble import RandomForestClassifier

In [17]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [18]:
random_forest = RandomForestClassifier(criterion='gini',random_state=42)
random_forest.fit(X_sm, Y_sm)
y_pred_random_forest = random_forest.predict(X_test)

In [19]:
acc = accuracy_score(y_test, y_pred_random_forest)
prec_macro = precision_score(y_test,y_pred_random_forest, average='macro')
recall_macro = recall_score(y_test, y_pred_random_forest, average='macro')
f1_macro = f1_score(y_test,y_pred_random_forest, average='macro')
classification_rep_RF = classification_report(y_test,y_pred_random_forest)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF = confusion_matrix(y_test, y_pred_random_forest)
print("Confusion Matrix:")
print(cf_matrix_RF)
print("\nClassification Report:\n", classification_rep_RF)

Accuracy Score: 0.65361869895804
Precision (Macro): 0.5755755039800202
Recall (Macro): 0.6212578459489014
F1 Score (Macro): 0.5875920007065857
Confusion Matrix:
[[ 34  28   8   1   0   2]
 [ 95 532 141  70   8   1]
 [ 19 132 298 109  11   6]
 [ 19  45 157 939 137  30]
 [  1   0   4  77 207  49]
 [  1   0   2  15  62 311]]

Classification Report:
               precision    recall  f1-score   support

           0       0.20      0.47      0.28        73
           1       0.72      0.63      0.67       847
           2       0.49      0.52      0.50       575
           3       0.78      0.71      0.74      1327
           4       0.49      0.61      0.54       338
           5       0.78      0.80      0.79       391

    accuracy                           0.65      3551
   macro avg       0.58      0.62      0.59      3551
weighted avg       0.68      0.65      0.66      3551



In [20]:
y_pred_train_RF = random_forest.predict(X_sm)
acc = accuracy_score(Y_sm, y_pred_train_RF )
prec_macro = precision_score(Y_sm,y_pred_train_RF , average='macro')
recall_macro = recall_score(Y_sm, y_pred_train_RF, average='macro')
f1_macro = f1_score(Y_sm, y_pred_train_RF , average='macro')
classification_rep_RF_train = classification_report(Y_sm,y_pred_train_RF )
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_train = confusion_matrix(Y_sm, y_pred_train_RF)
print("Confusion Matrix:")
print(cf_matrix_RF_train)
print("\nClassification Report:\n", classification_rep_RF_train)

Accuracy Score: 1.0
Precision (Macro): 1.0
Recall (Macro): 1.0
F1 Score (Macro): 1.0
Confusion Matrix:
[[3221    0    0    0    0    0]
 [   0 3221    0    0    0    0]
 [   0    0 3221    0    0    0]
 [   0    0    0 3221    0    0]
 [   0    0    0    0 3221    0]
 [   0    0    0    0    0 3221]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3221
           1       1.00      1.00      1.00      3221
           2       1.00      1.00      1.00      3221
           3       1.00      1.00      1.00      3221
           4       1.00      1.00      1.00      3221
           5       1.00      1.00      1.00      3221

    accuracy                           1.00     19326
   macro avg       1.00      1.00      1.00     19326
weighted avg       1.00      1.00      1.00     19326



In [21]:
### After tuning 

In [22]:
##### Tuning -Random search CV

In [23]:

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              }

In [24]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all a+vailable cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=0, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_sm, Y_sm)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=0, verbose=2)

In [25]:
rf_random.best_params_

{'n_estimators': 400,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'auto',
 'max_depth': 80}

In [26]:
best_RF_RCV = RandomForestClassifier(n_estimators= 1800,
 min_samples_split= 2,
 min_samples_leaf=1,
 max_features= 'sqrt',
 max_depth= 80,
 )
best_RF_RCV.fit(X_sm, Y_sm)
y_pred_RF_RCV = best_RF_RCV.predict(X_test)

In [27]:
acc = accuracy_score(y_test, y_pred_RF_RCV)
prec_macro = precision_score(y_test,y_pred_RF_RCV, average='macro')
recall_macro = recall_score(y_test, y_pred_RF_RCV, average='macro')
f1_macro = f1_score(y_test,y_pred_RF_RCV, average='macro')
classification_rep_RF_RCV = classification_report(y_test,y_pred_RF_RCV)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_rcv = confusion_matrix(y_test, y_pred_RF_RCV)
print("Confusion Matrix:")
print(cf_matrix_RF_rcv)
print("\nClassification Report:\n", classification_rep_RF_RCV)

Accuracy Score: 0.6541819205857505
Precision (Macro): 0.5782880333066148
Recall (Macro): 0.626815799498144
F1 Score (Macro): 0.591421412977432
Confusion Matrix:
[[ 37  25   7   2   0   2]
 [ 89 536 144  70   7   1]
 [ 18 135 291 114  10   7]
 [ 20  44 155 942 137  29]
 [  1   0   4  77 207  49]
 [  1   0   1  17  62 310]]

Classification Report:
               precision    recall  f1-score   support

           0       0.22      0.51      0.31        73
           1       0.72      0.63      0.68       847
           2       0.48      0.51      0.49       575
           3       0.77      0.71      0.74      1327
           4       0.49      0.61      0.54       338
           5       0.78      0.79      0.79       391

    accuracy                           0.65      3551
   macro avg       0.58      0.63      0.59      3551
weighted avg       0.68      0.65      0.66      3551



In [28]:
y_pred_RF_RCV_train = best_RF_RCV.predict(X_sm)

In [29]:
acc = accuracy_score(Y_sm, y_pred_RF_RCV_train)
prec_macro = precision_score(Y_sm,y_pred_RF_RCV_train, average='macro')
recall_macro = recall_score(Y_sm, y_pred_RF_RCV_train, average='macro')
f1_macro = f1_score(Y_sm,y_pred_RF_RCV_train, average='macro')
classification_rep_RF_RCV_Train = classification_report(Y_sm,y_pred_RF_RCV_train)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_rcv_train = confusion_matrix(Y_sm, y_pred_RF_RCV_train)
print("Confusion Matrix:")
print(cf_matrix_RF_rcv_train)
print("\nClassification Report:\n", classification_rep_RF_RCV_Train)

Accuracy Score: 1.0
Precision (Macro): 1.0
Recall (Macro): 1.0
F1 Score (Macro): 1.0
Confusion Matrix:
[[3221    0    0    0    0    0]
 [   0 3221    0    0    0    0]
 [   0    0 3221    0    0    0]
 [   0    0    0 3221    0    0]
 [   0    0    0    0 3221    0]
 [   0    0    0    0    0 3221]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3221
           1       1.00      1.00      1.00      3221
           2       1.00      1.00      1.00      3221
           3       1.00      1.00      1.00      3221
           4       1.00      1.00      1.00      3221
           5       1.00      1.00      1.00      3221

    accuracy                           1.00     19326
   macro avg       1.00      1.00      1.00     19326
weighted avg       1.00      1.00      1.00     19326



In [30]:
### Gridsearch CV

In [31]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [rf_random.best_params_['max_depth']],
    'max_features': [rf_random.best_params_['max_features']],
    'min_samples_leaf': [rf_random.best_params_['min_samples_leaf'], 
                         rf_random.best_params_['min_samples_leaf']+2, 
                         rf_random.best_params_['min_samples_leaf'] + 4],
    'min_samples_split': [rf_random.best_params_['min_samples_split'] - 2,
                          rf_random.best_params_['min_samples_split'] - 1,
                          rf_random.best_params_['min_samples_split'], 
                          rf_random.best_params_['min_samples_split'] +1,
                          rf_random.best_params_['min_samples_split'] + 2],
    'n_estimators': [rf_random.best_params_['n_estimators'] - 200, rf_random.best_params_['n_estimators'] - 100, 
                     rf_random.best_params_['n_estimators'], 
                     rf_random.best_params_['n_estimators'] + 100, rf_random.best_params_['n_estimators'] + 200]
}

print(param_grid)
# Create a based model


{'max_depth': [80], 'max_features': ['auto'], 'min_samples_leaf': [1, 3, 5], 'min_samples_split': [0, 1, 2, 3, 4], 'n_estimators': [200, 300, 400, 500, 600]}


In [32]:
RF = RandomForestClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = RF, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)
grid_search.fit(X_sm,Y_sm)

Fitting 3 folds for each of 75 candidates, totalling 225 fits


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
90 fits failed out of a total of 225.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\ProgramData\anaconda3\Lib\site-packag

GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [80], 'max_features': ['auto'],
                         'min_samples_leaf': [1, 3, 5],
                         'min_samples_split': [0, 1, 2, 3, 4],
                         'n_estimators': [200, 300, 400, 500, 600]},
             verbose=2)

In [33]:
grid_search.best_estimator_

RandomForestClassifier(max_depth=80, max_features='auto', n_estimators=200)

In [34]:
best_RF_GCV=RandomForestClassifier(max_depth=80, min_samples_split=4, n_estimators=2000)
best_RF_GCV.fit(X_sm,Y_sm)

RandomForestClassifier(max_depth=80, min_samples_split=4, n_estimators=2000)

In [35]:
y_pred_RF_GCV = best_RF_GCV.predict(X_test)

In [36]:


acc = accuracy_score(y_test, y_pred_RF_GCV)
prec_macro = precision_score(y_test,y_pred_RF_GCV, average='macro')
recall_macro = recall_score(y_test, y_pred_RF_GCV, average='macro')
f1_macro = f1_score(y_test,y_pred_RF_GCV, average='macro')
classification_rep_RF_GCV = classification_report(y_test,y_pred_RF_GCV)
print("Accuracy Score:", acc)
print("Precision (Macro):", prec_macro)
print("Recall (Macro):", recall_macro)
print("F1 Score (Macro):", f1_macro)

# Confusion Matrix
cf_matrix_RF_gcv = confusion_matrix(y_test, y_pred_RF_GCV)
print("Confusion Matrix:")
print(cf_matrix_RF_gcv)
print("\nClassification Report:\n", classification_rep_RF_GCV)

Accuracy Score: 0.6567164179104478
Precision (Macro): 0.5818384162097757
Recall (Macro): 0.630245024882406
F1 Score (Macro): 0.5948706655994768
Confusion Matrix:
[[ 37  25   7   2   0   2]
 [ 87 539 144  70   7   0]
 [ 19 132 298 110   9   7]
 [ 19  45 157 939 138  29]
 [  1   0   3  75 212  47]
 [  1   0   2  17  64 307]]

Classification Report:
               precision    recall  f1-score   support

           0       0.23      0.51      0.31        73
           1       0.73      0.64      0.68       847
           2       0.49      0.52      0.50       575
           3       0.77      0.71      0.74      1327
           4       0.49      0.63      0.55       338
           5       0.78      0.79      0.78       391

    accuracy                           0.66      3551
   macro avg       0.58      0.63      0.59      3551
weighted avg       0.68      0.66      0.66      3551



In [37]:
y_pred_RF_GCV_train = best_RF_GCV.predict(X_sm)

In [38]:
acc1 = accuracy_score(Y_sm, y_pred_RF_GCV_train)
prec_macro1 = precision_score(Y_sm,y_pred_RF_GCV_train, average='macro')
recall_macro1 = recall_score(Y_sm, y_pred_RF_GCV_train, average='macro')
f1_macro1 = f1_score(Y_sm,y_pred_RF_GCV_train, average='macro')
classification_rep_RF_GCV_Train = classification_report(Y_sm,y_pred_RF_GCV_train)
print("Accuracy Score:", acc1)
print("Precision (Macro):", prec_macro1)
print("Recall (Macro):", recall_macro1)
print("F1 Score (Macro):", f1_macro1)

# Confusion Matrix
cf_matrix_RF_gcv_train = confusion_matrix(Y_sm, y_pred_RF_GCV_train)
print("Confusion Matrix:")
print(cf_matrix_RF_gcv_train)
print("\nClassification Report:\n", classification_rep_RF_GCV_Train)

Accuracy Score: 0.9983959432888337
Precision (Macro): 0.9983979775689158
Recall (Macro): 0.998395943288834
F1 Score (Macro): 0.998396190722505
Confusion Matrix:
[[3221    0    0    0    0    0]
 [   1 3210    0    8    1    1]
 [   0    0 3217    2    1    1]
 [   1    2    0 3212    0    6]
 [   0    0    0    3 3216    2]
 [   0    0    1    1    0 3219]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3221
           1       1.00      1.00      1.00      3221
           2       1.00      1.00      1.00      3221
           3       1.00      1.00      1.00      3221
           4       1.00      1.00      1.00      3221
           5       1.00      1.00      1.00      3221

    accuracy                           1.00     19326
   macro avg       1.00      1.00      1.00     19326
weighted avg       1.00      1.00      1.00     19326

